config/routes.rb
Rails.application.routes.draw do
  resources :birthdays
  post 'buscar', to: 'birthdays#index'
  root 'birthdays#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/birthday.rb
class Birthday < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/birthdays_controller.rb
class BirthdaysController < ApplicationController
  before_action :set_birthday, only: [:show, :edit, :update, :destroy]

  # GET /birthdays
  # GET /birthdays.json
  def index
    if params[:search].present?
      @birthdays = Birthday.where("name like?", "%#{params[:search]}%")
    else
      @birthdays = Birthday.all
    end

  end

  # GET /birthdays/1
  # GET /birthdays/1.json
  def show
  end

  # GET /birthdays/new
  def new
    @birthday = Birthday.new
  end

  # GET /birthdays/1/edit
  def edit
  end

  # POST /birthdays
  # POST /birthdays.json
  def create
    @birthday = Birthday.new(birthday_params)

    respond_to do |format|
      if @birthday.save
        format.html { redirect_to @birthday, notice: 'Birthday was successfully created.' }
        format.json { render :show, status: :created, location: @birthday }
      else
        format.html { render :new }
        format.json { render json: @birthday.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /birthdays/1
  # PATCH/PUT /birthdays/1.json
  def update
    respond_to do |format|
      if @birthday.update(birthday_params)
        format.html { redirect_to @birthday, notice: 'Birthday was successfully updated.' }
        format.json { render :show, status: :ok, location: @birthday }
      else
        format.html { render :edit }
        format.json { render json: @birthday.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /birthdays/1
  # DELETE /birthdays/1.json
  def destroy
    @birthday.destroy
    respond_to do |format|
      format.html { redirect_to birthdays_url, notice: 'Birthday was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  def buscador
    
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_birthday
      @birthday = Birthday.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def birthday_params
      params.require(:birthday).permit(:b_day, :name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/birthdays_helper.rb
module BirthdaysHelper
end

app/views/birthdays/_form.html.erb
<%= form_for(birthday) do |f| %>
  <% if birthday.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(birthday.errors.count, "error") %> prohibited this birthday from being saved:</h2>

      <ul>
      <% birthday.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :b_day %>
    <%= f.date_select :b_day, {:start_year => 1980 }%>
  </div>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/birthdays/edit.html.erb
<h1>Editing Birthday</h1>

<%= render 'form', birthday: @birthday %>

<%= link_to 'Show', @birthday %> |
<%= link_to 'Back', birthdays_path %>

app/views/birthdays/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Birthdays</h1>
<%= form_tag(buscar_path) do %>
  <%= text_field_tag "search", nil, placeholder: "buscador", class: "class" %>
  <%= submit_tag "Enviar", class:"class" %>

  
<% end %>


<table>
  <thead>
    <tr>
      <th>Fecha</th>
      <td> Nombre</td>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @birthdays.each do |birthday| %>
      <tr>
        <td><%= birthday.b_day %></td>
        <td><%= birthday.name %></td>
        <td><%= link_to 'Show', birthday %></td>
        <td><%= link_to 'Edit', edit_birthday_path(birthday) %></td>
        <td><%= link_to 'Destroy', birthday, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Birthday', new_birthday_path %>

app/views/birthdays/new.html.erb
<h1>New Birthday</h1>

<%= render 'form', birthday: @birthday %>

<%= link_to 'Back', birthdays_path %>

app/views/birthdays/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>B day:</strong>
  <%= @birthday.b_day %>
</p>

<p>
  <strong>Nombre:</strong>
  <%= @birthday.name %>
</p>

<%= link_to 'Edit', edit_birthday_path(@birthday) %> |
<%= link_to 'Back', birthdays_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CumpleaOs2</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>